version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    container_name: tweet-zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    container_name: tweet-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#    depends_on:
#      - "zookeeper"
  userservice:
    image: userservice:latest
    container_name: userservice
    ports:
      - "8082:8082"
    build:
      context: .
#    depends_on:
#      - mycassandra
  tweetservice:
    image: tweetservice:latest
    container_name: tweetservice
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:29092
    ports:
      - "8083:8083"
    build:
      context: .
    depends_on:
      - userservice
      - kafka
    links:
      - userservice
      - kafka

#version: '3.1'
#services:
#
#  zookeeper:
#    image: wurstmeister/zookeeper:3.4.6
#    container_name: tweet-zookeeper
#    ports:
#      - "2181:2181"
#  kafka:
#    image: wurstmeister/kafka:2.13-2.6.0
#    container_name: tweet-kafka
#    ports:
#      - "9092:9092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#    depends_on:
#      - "zookeeper"